Open terminal and type:
$ dbit init 

#Create a new project called nyc_parking_violations
#Enter a number: 1 - says no sample profile found and hence we create one:

$ cd new_york_parking_violations/
$ touch profiles.yml

This will create a new profiles.yml file and add the content:
new_york_parking_violations:
  outputs:
    dev:
        type:duckdb
    target: dev
